language: node_js

os:
  - linux
  - osx

node_js:
  - "8"

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn config set no-progress
  - yarn install --silent
  - yarn "npm:build"
  - yarn "docs:build"
  - yarn "storybook:build"

script:
  - yarn tslint
  - yarn config set no-progress
  - yarn install --silent
  - yarn test --coverage --runInBand
